name: vyshu_ai
description: Vyshu AI V4 - Personal AI Secretary by Teja
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  connectivity_plus: ^6.0.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.0
  torch_light: ^1.0.2
  volume_controller: ^2.0.7
  screen_brightness: ^0.2.2+1
  url_launcher: ^6.2.5
  android_intent_plus: ^4.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  mailer: ^6.1.0
  intl: ^0.19.0
  image_picker: ^1.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/vyshu_logo.png
    - assets/vyshu/office/outfit_1.png
    - assets/rooms/.keep
    - assets/vyshu/home/.keep
    - assets/vyshu/adaptive/.keep
